[supervisord]
nodaemon=true
logfile = /dev/null
loglevel = debug

[supervisorctl]

[program:uvicorn]
command=python-project-stater server start
process_name=%(program_name)s_%(process_num)s
numprocs=1
user=ubuntu

[program:celery]
command=python-project-starter processor_celery start
process_name=%(program_name)s_%(process_num)s
numprocs=1
user=ubuntu