services:
  dev:
    image: ${PROJECT_NAME}:latest
    container_name: ${PROJECT_NAME}-dev
    build: 
      context: .
      dockerfile: dockerfile
      args:
        - BUILD_VERSION=DEV
        - WORKDIR=/Projects/${PROJECT_NAME}
    # platform: linux/amd64
    ports:
      - 8000:8000
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/Projects/${PROJECT_NAME}:cached
      - venv:/Projects/${PROJECT_NAME}/.venv
      - python:/Projects/${PROJECT_NAME}/.python
      - uv_cache:/Projects/${PROJECT_NAME}/.uv_cache
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 

volumes:
  venv:
  python:
  uv_cache: